
//DEFINE CONSTANTS FOR EACH ACTION THAT IS PERFORMED ON UI
export const ActionTypes = {
    SET_PRODUCT: "SET_PRODUCT",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    CALCULATE_BILL: "CALCULATE_BILL",
    SET_CART: "SET_CART"
}